export { default as TeacherDashboard } from './TeacherDashboard'
export { default as ManageAccounts } from './ManageAccounts'
export { default as MonitorStudents } from './MonitorStudents'
export { default as StudentDetail } from './StudentDetail'
export { default as TeacherRanking } from './TeacherRanking'
